name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: todo

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Gradle Project
        uses: com-nimeji/gradle-build@main
        with:
          java-version: 17
      - name: Build and push Docker Image
        uses: com-nimeji/docker-build@main
        with:
          image-name: todo
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment todo-app
